/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyse Sentence */
        post: operations["analyse_sentence_analyse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjectiveMorphology */
        AdjectiveMorphology: {
            /** Degree */
            degree?: ("positive" | "comparative" | "superlative") | null;
        };
        /** AdjectiveToken */
        AdjectiveToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /**
             * Lemma
             * @description The lemma or base form of the original word.
             */
            lemma: string;
            /**
             * Part Of Speech
             * @description The category of the word derived from the universal part of speech tag.
             */
            part_of_speech: ("noun" | "numeral" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection") | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
            morphology: components["schemas"]["AdjectiveMorphology"];
        };
        /** AnalyseRequest */
        AnalyseRequest: {
            /**
             * Sentence
             * @description Swedish text to analyse
             */
            sentence: string;
        };
        /** AnalyseResponse */
        AnalyseResponse: {
            /** Tokens */
            tokens: (components["schemas"]["NounToken"] | components["schemas"]["VerbToken"] | components["schemas"]["AdjectiveToken"] | components["schemas"]["PronounToken"] | components["schemas"]["BaseToken"])[];
        };
        /** BaseToken */
        BaseToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /**
             * Lemma
             * @description The lemma or base form of the original word.
             */
            lemma: string;
            /**
             * Part Of Speech
             * @description The category of the word derived from the universal part of speech tag.
             */
            part_of_speech: ("noun" | "numeral" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection") | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
        };
        /**
         * Definition
         * @description Public API representation of a definition.
         */
        Definition: {
            /** Translations */
            translations: string[];
            /** Definition */
            definition?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** NounMorphology */
        NounMorphology: {
            /** Gender */
            gender?: ("common" | "neuter") | null;
            /** Definiteness */
            definiteness?: ("definite" | "indefinite") | null;
            /** Plurality */
            plurality?: ("singular" | "plural") | null;
        };
        /** NounToken */
        NounToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /**
             * Lemma
             * @description The lemma or base form of the original word.
             */
            lemma: string;
            /**
             * Part Of Speech
             * @description The category of the word derived from the universal part of speech tag.
             */
            part_of_speech: ("noun" | "numeral" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection") | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
            morphology: components["schemas"]["NounMorphology"];
        };
        /** PronounMorphology */
        PronounMorphology: {
            /**
             * Form
             * @enum {string}
             */
            form: "object" | "possessive" | "subject";
        };
        /** PronounToken */
        PronounToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /**
             * Lemma
             * @description The lemma or base form of the original word.
             */
            lemma: string;
            /**
             * Part Of Speech
             * @description The category of the word derived from the universal part of speech tag.
             */
            part_of_speech: ("noun" | "numeral" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection") | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
            morphology: components["schemas"]["PronounMorphology"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerbMorphology */
        VerbMorphology: {
            /** Tense */
            tense?: ("past tense" | "present tense") | null;
            /** Form */
            form?: ("infinitive" | "supine" | "imperative") | null;
        };
        /** VerbToken */
        VerbToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /**
             * Lemma
             * @description The lemma or base form of the original word.
             */
            lemma: string;
            /**
             * Part Of Speech
             * @description The category of the word derived from the universal part of speech tag.
             */
            part_of_speech: ("noun" | "numeral" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection") | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
            morphology: components["schemas"]["VerbMorphology"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    analyse_sentence_analyse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
