/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyse Sentence */
        post: operations["analyse_sentence_analyse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/define": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Define Word */
        post: operations["define_word_define_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyseRequest */
        AnalyseRequest: {
            /**
             * Sentence
             * @description Swedish text to analyse
             */
            sentence: string;
        };
        /** AnalyseResponse */
        AnalyseResponse: {
            /** Tokens */
            tokens: (components["schemas"]["NounToken"] | components["schemas"]["VerbToken"] | components["schemas"]["PronounToken"] | components["schemas"]["BaseToken"])[];
        };
        /** BaseToken */
        BaseToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /** @description The category of the word derived from the universal part of speech tag. */
            part_of_speech: components["schemas"]["PartOfSpeech"] | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
        };
        /** DefineRequest */
        DefineRequest: {
            /**
             * Text
             * @description The word to look up
             */
            text: string;
            /**
             * Pos
             * @description Optional part of speech for filtering
             */
            pos?: ("noun" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection" | "punctuation") | null;
        };
        /** DefineResponse */
        DefineResponse: {
            /**
             * Text
             * @description The word that was looked up
             */
            text: string;
            /**
             * Pos
             * @description Part of speech used for filtering
             */
            pos: ("noun" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection" | "punctuation") | null;
            /**
             * Definitions
             * @description Dictionary definitions filtered by part of speech
             */
            definitions: components["schemas"]["Definition"][];
        };
        /**
         * Definition
         * @description Public API representation of a definition.
         */
        Definition: {
            /** Translations */
            translations: string[];
            /** Definition */
            definition?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NounMorphology */
        NounMorphology: {
            /** Gender */
            gender?: ("common" | "neuter") | null;
            /** Definiteness */
            definiteness?: ("definite" | "indefinite") | null;
            /** Plurality */
            plurality?: ("singular" | "plural") | null;
        };
        /** NounToken */
        NounToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /** @description The category of the word derived from the universal part of speech tag. */
            part_of_speech: components["schemas"]["PartOfSpeech"] | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
            morphology: components["schemas"]["NounMorphology"];
        };
        /** PartOfSpeech */
        PartOfSpeech: {
            /** Title */
            title: string;
            /**
             * Id
             * @enum {string}
             */
            id: "noun" | "verb" | "auxiliary_verb" | "adjective" | "adverb" | "pronoun" | "determiner" | "conjunction" | "preposition" | "interjection" | "punctuation";
        };
        /** PronounMorphology */
        PronounMorphology: {
            /**
             * Form
             * @enum {string}
             */
            form: "object" | "possessive" | "subject";
        };
        /** PronounToken */
        PronounToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /** @description The category of the word derived from the universal part of speech tag. */
            part_of_speech: components["schemas"]["PartOfSpeech"] | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
            morphology: components["schemas"]["PronounMorphology"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerbMorphology */
        VerbMorphology: {
            /** Tense */
            tense?: ("past tense" | "present tense") | null;
            /** Form */
            form?: ("infinitive" | "supine" | "imperative") | null;
        };
        /** VerbToken */
        VerbToken: {
            /**
             * Text
             * @description The original word in the given text.
             */
            text: string;
            /** @description The category of the word derived from the universal part of speech tag. */
            part_of_speech: components["schemas"]["PartOfSpeech"] | null;
            /**
             * Definitions
             * @description Dictionary definitions for this word
             */
            definitions?: components["schemas"]["Definition"][];
            morphology: components["schemas"]["VerbMorphology"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyse_sentence_analyse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    define_word_define_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
